# Generated by Django 3.2.6 on 2021-08-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meters',
            name='rate_name',
        ),
        migrations.AlterField(
            model_name='meters',
            name='day_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meters',
            name='night_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meters',
            name='weekend_Rate',
            field=models.FloatField(),
        ),
    ]
