# Generated by Django 3.2.6 on 2021-08-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0002_auto_20210809_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meters',
            old_name='default_street_address1',
            new_name='Customer_Address',
        ),
        migrations.RenameField(
            model_name='meters',
            old_name='customer_name',
            new_name='Customer_Name',
        ),
        migrations.RenameField(
            model_name='meters',
            old_name='day_rate',
            new_name='Day_Rate',
        ),
        migrations.RenameField(
            model_name='meters',
            old_name='meter_number',
            new_name='Meter_Number',
        ),
        migrations.RenameField(
            model_name='meters',
            old_name='night_rate',
            new_name='Night_Rate',
        ),
        migrations.RenameField(
            model_name='meters',
            old_name='weekend_Rate',
            new_name='eekend_Rate',
        ),
        migrations.AddField(
            model_name='meters',
            name='Rate_Name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
