# Generated by Django 3.2.6 on 2021-08-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0003_auto_20210810_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meters',
            old_name='eekend_Rate',
            new_name='Weekend_Rate',
        ),
    ]
