# Generated by Django 3.2.6 on 2021-08-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0004_rename_eekend_rate_meters_weekend_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meters',
            name='Day_Rate',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
