# Generated by Django 3.2.6 on 2021-08-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0006_auto_20210810_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meters',
            name='Customer_Name',
            field=models.CharField(max_length=100, verbose_name='Customer Name'),
        ),
    ]
