# Generated by Django 3.2.6 on 2021-08-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0007_alter_meters_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meters',
            name='Customer_Name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Customer Name'),
        ),
    ]
