# Generated by Django 3.2.6 on 2021-08-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0008_alter_meters_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meters',
            old_name='Customer_Address',
            new_name='customer_address',
        ),
        migrations.RenameField(
            model_name='meters',
            old_name='Customer_Name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='meters',
            old_name='Day_Rate',
            new_name='day_rate',
        ),
        migrations.RenameField(
            model_name='meters',
            old_name='Meter_Number',
            new_name='meter_number',
        ),
        migrations.RenameField(
            model_name='meters',
            old_name='Night_Rate',
            new_name='night_rate',
        ),
        migrations.RenameField(
            model_name='meters',
            old_name='Rate_Name',
            new_name='rate_name',
        ),
        migrations.RenameField(
            model_name='meters',
            old_name='Weekend_Rate',
            new_name='weekend_rate',
        ),
    ]
