# Generated by Django 3.2.6 on 2021-08-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0009_auto_20210811_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='meters',
            name='cost_for_day_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='meters',
            name='cost_for_night_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='meters',
            name='cost_for_weekend_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='meters',
            name='total_energy_cost',
            field=models.FloatField(null=True),
        ),
    ]
