# Generated by Django 3.2.6 on 2021-08-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0010_auto_20210811_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meters',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Name'),
        ),
    ]
