# Generated by Django 3.2.6 on 2021-08-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0011_alter_meters_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meters',
            name='meter_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
