# Generated by Django 3.2.6 on 2021-08-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0012_alter_meters_meter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meters',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
